ftlabs/left

- bin/lib/api.js
- bin/lib/deepl.js
- bin/lib/google.js
- bin/lib/multi-translator.js
- bin/lib/utils/translator-settings.js
- bin/lib/utils/utils.js
- index.js
- package-lock.json
- package.json
- public/js/main.js
- views/index.hbs
- added s3o
- restricted translator usage to selected s3o users
- initial setup for translator settings
> [FEATURE] S3O

- bin/lib/aws.js
- bin/lib/deepl.js
- bin/lib/google.js
- bin/lib/multi-translator.js
- bin/lib/utils/utils.js
- index.js
- package-lock.json
- package.json
- public/css/main.css
- public/js/main.js
- views/index.hbs
- Adds Amazon Translate
- Adds String splitting by paragraph and bytesize
- Dynamic front-end
> [FEATURE] AWS

- bin/lib/aws.js
- bin/lib/deepl.js
- bin/lib/google.js
- bin/lib/multi-translator.js
- bin/lib/utils/translator-settings.js
- public/css/main.css
- public/js/main.js
- views/index.hbs
-Tidy up form settings
- Clean up space for results
- Add loading visual
> [Feature] Client

- bin/lib/aws.js
- bin/lib/deepl.js
- bin/lib/google.js
- index.js
- public/css/main.css
- public/js/main.js
- handle translators and CAPI errors
> [FEATURE] Error handling

- index.js
Added credential file creation from env vars for Google Translate.
> [FEATURE] Google deploy creds

- index.js
- package-lock.json
- package.json
> [AMEND] SSL config

- public/css/main.css
- public/js/main.js
- views/index.hbs
A JS solution to standardising the heights for each paragraph in the article so that when comparing the translations they line up.
> Standardisation of paragraph height

- index.js
Need to temporarily return file from `/public`
> [FIX] give access to public route

- index.js
- public/js/main.js
change Content-Type to avoid preflight conflict
> [AMEND] CORS

- index.js
- public/css/main.css
Add header tags and title to stand first as well as logic if stand first does not exist to not make it a header.
> Add header tags to title and stand first

- index.js
Left uses old cached translations because the `publishedDate` parameter does not correspond to the last modified date.
- When caching, save `lastModified` date as the `lastPubDate`
- Check the `lastModified` date with a CAPI call rather than relying on the client-side date (use it as backup instead of error).
None
Added `INCLUDE_LAST_MODIFIED_DATE` policy to CAPI key
> [FIX] last modified date

- bin/lib/aws/translation-cache-bucket.js
- bin/lib/aws/translation-cache-table.js
- bin/lib/ft/capi.js
- bin/lib/translators/aws.js
- bin/lib/translators/deepl.js
- bin/lib/translators/google.js
- bin/lib/translators/multi-translator.js
- bin/lib/utils/display-checks.js
- bin/lib/utils/tracking.js
- bin/lib/utils/translator-settings.js
- index.js
- adds tracking util
- converts console log to use Tracking.splunk (NB log drain needs to be set after deploy to Heroku)
- verbose error messages
> [Feature] tracking

- package-lock.json
- package.json
Patching vulnerability
Ran npm aupdate + updated lodash dependency depth 2
> [Patch] Dependencies

- index.js
> [FIX] reenable s3o

- public/js/component/main.js
- public/js/component/splitView.js
- views/partials/userTest/component.hbs
Fixes component view selection
Pulled down Jamie's changes
> [Fix] component view selection

- index.js
Adds Tracking for user-testing route
Log to splunk (drain still in place)
> [Update] Tracking

- package.json
Updating s3o middleware so the app works locally.
> [Update package] Update s3o middleware.

- package-lock.json
- package.json
- public/css/translation-component.css
- public/js/componentSecondIteration/main.js
- public/js/componentSecondIteration/splitView.js
- views/content.hbs
- views/partials/userTest/componentSecondIteration.hbs
- views/partials/userTest/content1.hbs
- views/partials/userTest/content2.hbs
- views/partials/userTest/content3.hbs
- views/partials/userTest/shareBar.hbs
- views/partials/userTest/testWarning.hbs
Implementing the redesign of the translations modal as per Olgas new design. The new design implements the component as an overlay triggered from the share sidebar.
Other than the UI most of the changes have been to accommodate the use of o-overlay. o-overlay means that a lot of the component has to be loaded when the overlay is opened. There has been various issues with this but most of them have been solved. One of these that we couldn't find a work around for was when you have the translate all checkbox checked the overlay will open when you navigate to the article while the translation is applied.
> [Feature] Redesign modal

- .snyk
- package-lock.json
Reinstall nodes modules & run Snyk wizard
> [Patch] Reinstall node modules

- public/css/translation-component.css
- public/js/componentSecondIteration/main.js
- public/js/componentSecondIteration/splitView.js
- views/content.hbs
- views/partials/userTest/componentSecondIteration.hbs
- views/partials/userTest/shareBar.hbs
Ensure the translation component is accessible
- add keyboard tabbing to the share bar
- add Aria description on the share bar
- fix overlay keyboard accessibility by moving the back button to the end
> [Fix] Accessibility

- public/js/componentSecondIteration/main.js
- views/content.hbs
- Add o-tracking & init function
- change `category` to avoid confusion with live component
> [Fix] Client-side tracking

- index.js
- public/css/translation-component.css
- public/js/componentSecondIteration/main.js
- views/content.hbs
- views/partials/userTest/content4.hbs
- views/partials/userTest/content5.hbs
- views/partials/userTest/content6.hbs
Adds new articles
Adds styling tweaks for different article toppers
Update `USER_TEST_UUIDS`
> [UPDATE] Add new articles

- public/css/translation-component.css
- public/js/componentSecondIteration/splitView.js
- views/partials/userTest/componentSecondIteration.hbs
Assorted UX fixes
- x-axis overflow
- alignment of language code
- font
- view selection
- flag alignment
> [Fix] Last minute tweaks

- bin/lib/ft/capi.js
Updates http calls to api.ft.com to https calls
Used find and replace
n/a
n/a
n/a
> [Fix] api.ft.com https update

- package-lock.json
- package.json
> [Patch] update packages
